export const defaultCheckoutValues = {
  fullName: "",
  email: "",
  phone: "",
  zipCode: "",
  address: "",
  number: "",
  complement: "",
  city: "",
  state: "",
  paymentMethod: "credit-card",
  cardNumber: "",
  cardName: "",
  expiryDate: "",
  cvv: "",
};
